services:
    # pgadmin:
    #     image: dpage/pgadmin4:9
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: admin
    #     ports:
    #         - "8080:80"
    #     networks:
    #         - mynetwork
    #     depends_on:
    #         - db
    db:
        image: postgres:17
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dyslexia
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    pgdata:
